# Étape de construction
FROM node:16 as build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm install -g @angular/cli@16
RUN npm run build --prod

# Étape de production
FROM nginx:alpine
COPY --from=build /app/dist/frontend /usr/share/nginx/html
COPY nginx.conf /app/nginx.conf  
EXPOSE 80
EXPOSE 443
CMD ["nginx", "-g", "daemon off;"]
