server {
    listen 80;
    server_name izyglam.com;

    root /usr/share/nginx/html;
    index index.html;

    # --- SEO ---
    # sitemap dynamique servi par le backend
    location = /sitemap.xml {
        proxy_pass http://backend:3000/sitemap.xml;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # (optionnel mais recommandé) robots.txt
    # -> soit il est dans /usr/share/nginx/html/robots.txt (Angular assets)
    # -> soit tu peux aussi le servir via backend si tu préfères
    location = /robots.txt {
        try_files $uri =404;
    }

    # --- Backend ---
    location /api/ {
        proxy_pass http://backend:3000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /uploads/ {
        proxy_pass http://backend:3000/uploads/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # --- Frontend Angular SPA fallback ---
    location / {
        try_files $uri $uri/ /index.html;
    }
}
