const fs = require('fs');

// Dictionnaire complet de traductions français -> catalan
const translations = {
  'Barber': 'Barber',
  'Fitness': 'Fitness',
  'Aucune conversation': 'Sense converses',
  'Créer une conversation': 'Crear conversa',
  'Créer': 'Crear',
  'Ouvrir la liste des conversations': 'Obrir llista de converses',
  'Photo envoyée': 'Foto enviada',
  'Documents': 'Documents',
  'Client absent': 'Client absent',
  'Total': 'Total',
  'Glam for Business': 'Serveis de bellesa per a empreses',
  'Agenda': 'Agenda',
  'LinkedIn': 'LinkedIn',
  'Instagram': 'Instagram',
  'Un nail art minimaliste pour un effet élégant et moderne.': 'Nail art minimalista per a un efecte elegant i modern.',
  'Choisissez des couleurs audacieuses pour exprimer votre créativité.': 'Trieu colors atrevits per expressar la vostra creativitat.',
  'Un style vintage revisité pour un look unique !': 'Un estil vintage reinterpretat per a un look únic!',
  'Commencez votre post par une question engageante pour inciter à interagir.': 'Comença el teu post amb una pregunta atractiva per animar a la interacció.',
  'Optimisez vos visuels avec des couleurs vives et un texte clair.': 'Optimitza els teus visuals amb colors vius i text clar.',
  'Ajoutez un appel à l\'action clair, comme \'Cliquez sur le lien\' ou \'Partagez votre avis\'.': 'Afegeix una crida a l\'acció clara, com "Fes clic al enllaç" o "Comparteix la teva opinió".',
  'Utilisez des légendes courtes mais percutantes pour Instagram et Bluesky.': 'Utilitza llegendes curtes però impactants per a Instagram i Bluesky.',
  'Incluez des questions ouvertes pour encourager les commentaires.': 'Inclou preguntes obertes per animar als comentaris.',
  'Ajoutez des hashtags pertinents pour toucher un public plus large.': 'Afegeix hashtags rellevants per arribar a un públic més ampli.',
  'Ajoutez des statistiques ou des faits intéressants pour capter l\'attention.': 'Afegeix estadístiques o dades interessants per captar l\'atenció.',
  'Racontez une histoire captivante pour garder vos lecteurs engagés.': 'Explica una història captivadora per mantenir els teus lectors compromesos.',
  'Mettez en avant vos réussites ou celles de vos clients pour LinkedIn.': 'Destaca els teus èxits o els dels teus clients per a LinkedIn.',
  'Soyez authentique et montrez votre vraie personnalité.': 'Sigues autèntic i mostra la teva veritable personalitat.',
  'Analysez vos performances et ajustez votre stratégie en conséquence.': 'Analitza els teus resultats i ajusta la teva estratègia en conseqüència.',
  'Utilisez des emojis pour rendre votre contenu plus visuel et attrayant.': 'Utilitza emojis per fer el teu contingut més visual i atractiu.',
  'Postez à des heures stratégiques pour maximiser la portée.': 'Publica en hores estratègiques per maximitzar l\'abast.',
  'Intégrez des stories ou reels pour capter l\'attention rapidement.': 'Integra stories o reels per captar l\'atenció ràpidament.',
  'Utilisez des légendes captivantes qui donnent envie de cliquer sur \'Lire la suite\'.': 'Utilitza llegendes captivadores que donin ganes de fer clic a "Llegeix més".',
  'Partagez des anecdotes personnelles pour créer une connexion émotionnelle.': 'Comparteix anècdotes personals per crear una connexió emocional.',
  'Variez vos formats : images, vidéos, carrousels ou sondages.': 'Varia els teus formats: imatges, vídeos, carrusels o enquestes.',
  'Adaptez le ton de votre contenu en fonction de la plateforme utilisée.': 'Adapta el to del teu contingut segons la plataforma utilitzada.',
  'Mentionnez d\'autres utilisateurs ou marques pour élargir votre portée.': 'Menciona altres usuaris o marques per ampliar el teu abast.',
  'Testez différents styles visuels pour découvrir ce qui plaît le plus à votre audience.': 'Prova diferents estils visuals per descobrir el que més agrada a la teva audiència.',
  'Utilisez des vidéos courtes pour capter l\'attention rapidement.': 'Utilitza vídeos curts per captar l\'atenció ràpidament.',
  'Ajoutez des témoignages clients pour renforcer votre crédibilité.': 'Afegeix testimonis de clients per reforçar la teva credibilitat.',
  'Créez des sondages pour engager votre audience.': 'Crea enquestes per involucrar la teva audiència.',
  'Mettez en avant vos valeurs pour toucher votre public cible.': 'Destaca els teus valors per arribar al teu públic objectiu.',
  'Ajoutez un avant/après pour démontrer un impact clair.': 'Afegeix un abans/després per demostrar un impacte clar.',
  'Incorporez des citations inspirantes pour motiver votre audience.': 'Incorpora cites inspiradores per motivar la teva audiència.',
  'Ajoutez des légendes en storytelling pour raconter une histoire.': 'Afegeix llegendes en forma de narrativa per explicar una història.',
  'Adaptez vos hashtags à chaque publication pour maximiser la portée.': 'Adapta els teus hashtags a cada publicació per maximitzar l\'abast.',
  'Évitez de surcharger vos visuels avec trop de texte.': 'Evita sobrecarregar els teus visuals amb massa text.',
  'Répondez rapidement aux commentaires pour créer une relation.': 'Respon ràpidament als comentaris per crear una relació.',
  'Mettez en avant vos coulisses pour humaniser votre marque.': 'Destaca els teus bastidors per humanitzar la teva marca.',
  'Utilisez des photos authentiques plutôt que des banques d\'images.': 'Utilitza fotos autèntiques en lloc de bancs d\'imatges.',
  'Répétez vos messages clés régulièrement pour ancrer votre communication.': 'Repeteix els teus missatges clau regularment per ancorar la teva comunicació.',
  'Identifiez les moments forts de l\'année pour vos publications.': 'Identifica els moments forts de l\'any per a les teves publicacions.',
  'Utilisez les tendances actuelles pour surfer sur l\'actualité.': 'Utilitza les tendències actuals per navegar per l\'actualitat.',
  'Ajoutez des statistiques intéressantes pour capter l\'attention.': 'Afegeix estadístiques interessants per captar l\'atenció.',
  'Créez des carrousels pour raconter une histoire en plusieurs étapes.': 'Crea carrusels per explicar una història en diverses etapes.',
  'Mettez un lien clair dans votre bio pour diriger vos visiteurs.': 'Posa un enllaç clar a la teva biografia per dirigir els teus visitants.',
  'Créez un guide ou une checklist pour offrir de la valeur à votre audience.': 'Crea una guia o llista de verificació per oferir valor a la teva audiència.',
  'Ajoutez des GIF ou des stickers pour rendre vos stories plus dynamiques.': 'Afegeix GIFs o adhesius per fer les teves stories més dinàmiques.',
  'Utilisez des couleurs cohérentes avec votre branding.': 'Utilitza colors coherents amb el teu branding.',
  'Mettez en avant vos collaborateurs pour créer un sentiment d\'équipe.': 'Destaca els teus col·laboradors per crear un sentiment d\'equip.',
  'Rédigez vos posts comme si vous parliez directement à une personne.': 'Escriu els teus posts com si parlessis directament a una persona.',
  'Ajoutez des quiz interactifs pour augmenter l\'engagement.': 'Afegeix qüestionaris interactius per augmentar el compromís.',
  'Créez un sentiment d\'urgence avec des promotions limitées.': 'Crea un sentiment d\'urgència amb promocions limitades.',
  'Intégrez des photos avant/après pour montrer des résultats concrets.': 'Integra fotos abans/després per mostrar resultats concrets.',
  'Créez des collaborations avec d\'autres créateurs pour élargir votre audience.': 'Crea col·laboracions amb altres creadors per ampliar la teva audiència.',
  'Soyez transparent sur vos processus ou vos produits.': 'Sigues transparent sobre els teus processos o productes.',
  'Ajoutez des animations pour rendre vos vidéos plus dynamiques.': 'Afegeix animacions per fer els teus vídeos més dinàmics.',
  'Créez des posts éducatifs pour apporter de la valeur à votre audience.': 'Crea posts educatius per aportar valor a la teva audiència.',
  'Mettez en avant des retours d\'expérience pour instaurer la confiance.': 'Destaca retorns d\'experiència per instaurar la confiança.',
  'Soyez concis dans vos messages pour aller droit au but.': 'Sigues concís en els teus missatges per anar directe al gra.',
  'Utilisez des mots-clés pertinents pour augmenter la visibilité.': 'Utilitza paraules clau rellevants per augmentar la visibilitat.',
  'Créez un calendrier éditorial pour planifier vos publications.': 'Crea un calendari editorial per planificar les teves publicacions.',
  'Expérimentez avec des visuels minimalistes pour un impact visuel fort.': 'Experimenta amb visuals minimalistes per a un fort impacte visual.',
  'Intégrez des témoignages vidéo pour plus d\'authenticité.': 'Integra testimonis en vídeo per més autenticitat.',
  'Créez des posts humoristiques pour engager avec légèreté.': 'Crea posts humorístics per involucrar amb lleugeresa.',
  'Utilisez des graphiques ou infographies pour expliquer des idées complexes.': 'Utilitza gràfics o infografies per explicar idees complexes.',
  'Publiez régulièrement pour garder votre audience engagée.': 'Publica regularment per mantenir la teva audiència compromesa.',
  'Incluez des remerciements ou des célébrations pour créer de la gratitude.': 'Inclou agraïments o celebracions per crear gratitud.',
  'Paiement par crédit entreprise': 'Pagament amb crèdit empresarial',
  'Utiliser mon crédit d\'entreprise': 'Utilitzar el meu crèdit empresarial',
  'Mon crédit disponible :': 'El meu crèdit disponible:',
  'Pas de crédit d\'entreprise': 'Sense crèdit empresarial',
  'Informations du salon': 'Informació del saló',
  'Vérification professionnelle': 'Verificació professional',
  'Étape 2 sur 2 · Vos documents restent privés et protégés.': 'Pas 2 de 2 · Els teus documents romanen privats i protegits.',
  'Vérification de votre profil professionnel': 'Verificació del teu perfil professional',
  'Nous vérifions chaque professionnel pour protéger vos clients et votre réputation.': 'Verifiquem cada professional per protegir els teus clients i la teva reputació.',
  'Pièce d\'identité': 'Document d\'identitat',
  'Carte d\'identité, passeport ou titre de séjour en cours de validité.': 'Document d\'identitat, passaport o títol de residència vàlid.',
  'Extrait Kbis (optionnel)': 'Extracte Kbis (opcional)',
  'Recommandé si vous exercez via une société immatriculée.': 'Recomanat si treballes a través d\'una societat registrada.',
  'Téléverser un document': 'Pujar un document',
  'Formats acceptés : PDF, JPG, PNG · taille max 10 Mo.': 'Formats acceptats: PDF, JPG, PNG · mida màxima 10 MB.',
  'La pièce d\'identité et l\'assurance sont obligatoires pour activer votre profil.': 'El document d\'identitat i l\'assegurança són obligatoris per activar el teu perfil.',
  'Document manquant': 'Document faltant',
  'En cours de vérification': 'En procés de verificació',
  'Validé': 'Validat',
  'Refusé · nouveau document requis': 'Rebutjat · es requereix un nou document',
  'Envoyer les documents': 'Enviar documents',
  'Je compléterai plus tard': 'Completaré més tard',
  'Vos documents ont été envoyés pour vérification.': 'Els teus documents han estat enviats per a verificació.',
  'Impossible de téléverser vos documents pour le moment.': 'No és possible pujar els teus documents en aquest moment.',
  'La pièce d\'identité est obligatoire.': 'El document d\'identitat és obligatori.',
  'L\'assurance professionnelle est obligatoire.': 'L\'assegurança professional és obligatòria.',
  'Validés': 'Validats',
  'Non validés': 'No validats',
  'Inatif': 'Inactiu',
  'Statut': 'Estat',
  'Mes messages': 'Els meus missatges',
  'Prochain niveau': 'Següent nivell',
  'Niveau maximum atteint': 'Nivell màxim assolit',
  'encore {{count}} réservations': 'encara {{count}} reserves',
  'Confirmation': 'Confirmació',
  'Annuler': 'Cancel·lar',
  'Terminer': 'Finalitzar',
  'Supprimer': 'Suprimir',
  'Rechercher une prestation': 'Buscar un servei',
  'Email de l\'utilisateur': 'Correu de l\'usuari',
  'Que souhaitez-vous réserver ?': 'Què vols reservar?',
  'Choisissez une catégorie. Ensuite : prestation → moment → créneau.': 'Tria una categoria. Després: servei → moment → franja.',
  'Paiement sécurisé • Pros vérifiées • Support réactif': 'Pagament segur • Professionals verificats • Suport reactiu',
  'Prix clair avant paiement. Vous confirmez quand tout est OK.': 'Preu clar abans del pagament. Confirmes quan tot està bé.',
  'Quel moment vous arrange ?': 'Quin moment et va bé?',
  'On affichera uniquement les créneaux disponibles.': 'Mostrarem només les franjes disponibles.',
  'Aujourd\'hui': 'Avui',
  'Ce soir': 'Aquesta nit',
  'Demain': 'Demà',
  'Cette semaine': 'Aquesta setmana',
  'Voir les créneaux disponibles': 'Veure les franjes disponibles',
  'Paiement sécurisé • Modification possible avant paiement': 'Pagament segur • Modificació possible abans del pagament',
  'Créneaux disponibles': 'Franjes disponibles',
  'Sélectionnez un créneau pour continuer.': 'Selecciona una franja per continuar.',
  'Vous validez tout au récapitulatif avant paiement.': 'Valides tot al resum abans del pagament.',
  'Récapitulatif': 'Resum',
  'Vérifiez avant de passer au paiement.': 'Verifica abans de passar al pagament.',
  'Prestation': 'Servei',
  'Durée': 'Durada',
  'Quand': 'Quan',
  'Prix': 'Preu',
  'à partir de': 'a partir de',
  'Continuer vers paiement': 'Continuar cap al pagament',
  'Paiement sécurisé. Annulation selon conditions. Vous pourrez choisir de reprendre avec le même prestataire après la prestation.': 'Pagament segur. Cancel·lació segons condicions. Podràs triar de tornar a reservar amb el mateix proveïdor després del servei.',
  'Comment souhaitez-vous réserver ?': 'Com vols reservar?',
  'Réservez en 2 minutes — à domicile, paiement sécurisé.': 'Reserva en 2 minuts — a casa, pagament segur.',
  'Réservation rapide': 'Reserva ràpida',
  'Choisissez une prestation, on vous propose les créneaux.': 'Tria un servei, et proposem les franjes.',
  'Recommandé': 'Recomanat',
  'Choisir un prestataire': 'Tria un proveïdor',
  'Parcourez les profils et réservez dans l\'agenda.': 'Navega pels perfils i reserva a l\'agenda.',
  'Gratuit pendant 1 mois': 'Gratuït durant 1 mes'
};

// Fonction pour remplacer récursivement toutes les valeurs
function replaceAllValues(obj, translations) {
  const result = {};
  for (const key in obj) {
    if (typeof obj[key] === 'object' && !Array.isArray(obj[key])) {
      result[key] = replaceAllValues(obj[key], translations);
    } else {
      const value = obj[key];
      if (typeof value === 'string' && translations[value]) {
        result[key] = translations[value];
      } else {
        result[key] = value;
      }
    }
  }
  return result;
}

// Charger le fichier ca.json
const file = 'src/assets/i18n/ca.json';
const data = JSON.parse(fs.readFileSync(file, 'utf8'));
const replaced = replaceAllValues(data, translations);
fs.writeFileSync(file, JSON.stringify(replaced, null, 2), 'utf8');
console.log('✅ ca.json mis à jour avec toutes les traductions catalanes!');
