export const environment = {
  production: true,
  apiUrl: 'https://api.izyglam.com/api/',
  apiUrlNoAPI: 'https://api.izyglam.com/',
  imgStorageUrl: 'assets/images/',
  APIimgStorageUrl: 'https://api.izyglam.com/',
  allowedCountries: ['FR'],
  comingSoonCountries: ['EN', 'ES', 'IT', 'NL', 'PT'],
  comingSoonCountriesDate: '2025-01-01',
  comingSoonCountries2: ['SV', 'PL', 'DA', 'FI', 'DE'],
  comingSoonCountries2Date: '2027-01-01',
  webSocketUrl: 'wss://api.izyglam.com',
  RUNWAY_API_KEY: 'key_...',
  FACEBOOK_APP_ID: '...',
  INSTAGRAM_APP_ID: '...',
  LINKEDIN_APP_ID: '...',
  TIKTOK_APP_ID: '...',
  TIKTOK_APP_SECRET: '...',
  BLUESKY_APP_ID: 'none',
  FACEBOOK_REDIRECT_URI: 'https://izyglam.com/meta-login',
  INSTAGRAM_REDIRECT_URI: 'https://a908-2a01-cb04-ada-600-4dc4-9b5f-9ff4-e468.ngrok-free.app/insta-login',
  THREADS_REDIRECT_URI: 'https://izyglam.com/insta-login',
  LINKEDIN_REDIRECT_URI: 'https://izyglam.com/linkedin-login',
  TIKTOK_REDIRECT_URI: 'https://izyglam.com/tiktok-login',
  BLUESKY_REDIRECT_URI: 'none',
  X_APP_ID: 'VOTRE_APP_ID_TWITTER',
  X_REDIRECT_URI: 'https://izyglam.com/x-login',
  App_Android: "https://play.google.com/store/apps/details?id=com.izyglam.client",
  App_iOS: "",
  stripePublicKey: 'pk_test_...', // Remplacez par votre clé publique
  shopIzyGlam: "https://shop.izyglam.com/",
  coreIzyGlam: "https://izyglam.com/",
  TVA_RATE: 0.20,
  izyglamCompany: {
    brandName: "izyGlam",
    companyName: "IZYGLAM SAS",
    legalForm: "SAS",
    siret: "00000000000000",
    vatNumber: "FR00000000000",
    addressLine1: "Adresse ligne 1",
    addressLine2: "",
    postalCode: "75000",
    city: "Paris",
    country: "France",
    email: "contact@izyglam.com",
    phone: "+33 0 00 00 00 00",
    website: "https://izyglam.com",
    logoPath: "assets/images/logo/logo_true.png"
  }

};
